version: "3.7"
services:
        api-login:
                container_name: login_api
                image: 100400/com.springboot.login:0.1
                ports:
                        - "8083:8083"
                depends_on:
                        - db-login

        db-login:
                container_name: db_login
                image: 100400/db_login:0.1               
                ports:
                        - "5435:5435"

        api-asset-management:   
                container_name: assetmanagement_api
                image: 100400/com.springboot.assetmanagement:0.1
                ports: 
                        - "8084:8084"
                depends_on: 
                        - db-asset-management  

        db-asset-management:
                container_name: db_assetmanagement
                image: 100400/db_login:0.1               
                ports:
                        - "5436:5436"   

networks:
        default:
                name: "am_network"
